### PR TITLE
Change order of login parameters

### LINKED ISSUE #21: SSO Login fails due wrong params order
**Description**: The SSO Login on rpatchur makes the client crash, and it needs to be fixed and tested in newer clients to confirm if this still happens.
**Client Version**: 2015-09-16aRagexe
**What rpatchur does**: ``` "-1rag1" "-t:password" "username" ``` (results on a client crash)
**What rpatchur should do** ``` -t:password username server -1rag1``` (it works for me)
**Additional Info**: [Where i found the correct param order](https://rathena.org/board/topic/99701-guys-help-me-on-my-project-ultimate-launcher/?do=findComment&comment=276396)

And is important to know that the commas are sent to the emulator too. So it fails because the server receives "username" and tries to find an account including the commas, tested on a 2018 hercules emulator.

### PR DESCRIPTION
**Pull request by vstumpf**
Fixes #21 

I don't have a real client to test with, but I made a small app to print the args, here's the output:
```
D:\blah\CLA.exe
-t:asdfa
jkljk
1sak1
```

Sry am new to rust, if there's a better way let me know.

### CODE REVIEW

**Comment by waken22** [comment]
Just as reminder, i needed to change this to make SSO login work, because it was sending the "commas" to the emulator, at least it was happening to me, you need to test it :

**Comment by vstumpf** [comment]
Interesting, the program I tested with did not receive any quotes. It's a c++ program that loops through argv printing each arg on a new line. Later I'll set up a client and try.

**Comment by waken22** [comment]
Maybe the problem it's mine, that's why if someone can check it ;p

**Review by L1nkZ — COMMENTED** [review]
I guess the following would be more idiomatic:
```
let mut play_arguments: Vec<String> = vec![format!("-t:{}", login_params.password), login_params.login];
play_arguments.extend(
    webview
    .user_data()
    .patcher_config
    .play
    .arguments
    .iter()
    .cloned(),
);
```

But that's just nit-picking. The commit looks good to me :)

**Comment by L1nkZ** [comment]
Thanks for the PR! 😁
I'll try to test this out if you can't, when I find the time.

**Comment by waken22** [comment]
In my case if i don't pass the "server" argument the client crash, so... yes i guess it gonna be needed 👍

**Comment by vstumpf** [comment]
After all the changes, here's a packet dump:
```
[Debug]: --- 00-01-02-03-04-05-06-07-08-09-0A-0B-0C-0D-0E-0F   0123456789ABCDEF
[Debug]: 000 25 08 64 00 2E 00 00 00 00 6D 79 75 73 65 72 31   %.d......myuser1
[Debug]: 001 00 80 00 00 E3 84 6D 82 AC F0 19 00 9C DC FD 76   .�..�m���..���v
[Debug]: 002 FF FF FF FF A4 F0 19 00 4B DD FD 76 90 3B 06 10   ������..K��v�;..
[Debug]: 003 43 52 65 73 E0 30 22 10 00 00 00 00 41 41 2D 41   CRes�0".....AA-A
[Debug]: 004 41 2D 41 41 2D 41 41 2D 41 41 2D 41 41 31 37 32   A-AA-AA-AA-AA172
[Debug]: 005 2E 32 36 2E 31 34 34 2E 31 00 81 07 50 61 53 73   .26.144.1.�.PaSs
[Debug]: 006 57 6F 52 64                                       WoRd
[Status]: Request for connection of myuser1 (ip: 172.19.0.1)
```

**Comment by L1nkZ** [comment]
Alright, thanks a lot for testing this, I'm merging 👍

**Pull request merged**
